blank_issues_enabled: false
contact_links:
  - name: Bugs and support requests
    url: https://appcenter.ms
    about: Please report bugs and support requests using the App Center in-product support experience.
